import type { MetadataRoute } from "next";

/**
 * Static PWA manifest — no dynamic data, no headers/cookies/searchParams
 * access, so Next prerenders this into a static file at export time
 * (next.config.ts: output: "export"). Icons come from the compact
 * tiltmeter glyph (apps/web/public/brand/icon-192.png / icon-512.png),
 * generated by scripts/brand.mjs — the project's own identity, not the
 * chip maker's mark.
 */
// Required by output: "export" for a metadata route handler — same
// self-guard shape as every page's `export const dynamic = "error"`.
export const dynamic = "force-static";

const DESCRIPTION =
  "tiltmeter tells an operator when a new model release moves their agent harness off true — not how capable a model is in the abstract, but whether a specific skill description, tool schema, routing prompt, or output contract still fires the way it did last week.";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "tiltmeter",
    short_name: "tiltmeter",
    description: DESCRIPTION,
    start_url: "/",
    display: "standalone",
    theme_color: "#FAF7F2",
    background_color: "#FAF7F2",
    icons: [
      { src: "/brand/icon-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/brand/icon-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
