// SPEC §12/§14 M3: render evals/calibration/RESULTS.md and inject the
// README table between <!-- calibration:begin --> / <!-- calibration:end -->
// from evals/calibration/results/latest.json. Numbers are GENERATED, never
// hand-written. Mirrors the sibling repo's scripts/chaos-report.mjs pattern
// exactly (same --check drift gate, same "don't re-run the sim in --check"
// split of responsibilities).
//
//   node scripts/calibration-report.mjs           regenerate latest.json,
//                                                  RESULTS.md, and the README
//                                                  block (requires a build —
//                                                  imports the compiled dist)
//   node scripts/calibration-report.mjs --check    fail (exit 1) if the
//                                                  committed files differ from
//                                                  what latest.json renders —
//                                                  the CI drift gate. Reads
//                                                  ONLY the committed json;
//                                                  does not require a build.
//
// (Behavioural drift — latest.json itself no longer matching a fresh
// calibration run — is caught by the eval stage, which re-runs both sims
// in-process via evals/calibration.eval.test.ts.)
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const RESULTS_DIR = resolve(ROOT, "evals", "calibration", "results");
const LATEST = resolve(RESULTS_DIR, "latest.json");
const RESULTS_MD = resolve(ROOT, "evals", "calibration", "RESULTS.md");
const README = resolve(ROOT, "README.md");
const BEGIN = "<!-- calibration:begin -->";
const END = "<!-- calibration:end -->";

/** Deterministic thousands grouping — no locale, no ICU variance (matches the sibling repo's chaos-report.mjs). */
const fmt = (n) => String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
const pct = (x) => `${(x * 100).toFixed(1)}%`;

export function renderReadmeBlock(r) {
  const lines = [
    `**Calibration (SPEC §12)** — seeded simulation, \`B = ${fmt(r.bootstrapB)}\` bootstrap resamples per trial, \`${String(r.itemCount)}\`-item pool, \`${String(r.trials)}\` trials per gate:`,
    "",
    "| gate | bar | achieved |",
    "|---|---|---|",
    `| false-positive rate — 200 null pairs, identical per-item rates | ≤ 5% (CI gate: ≤ 8/200) | **${pct(r.falsePositive.rate)}** (${String(r.falsePositive.fires)}/${String(r.falsePositive.trials)}) |`,
    `| detection power — 200 pairs, planted 20% degradation (${String(r.degradedCount)} of ${String(r.itemCount)} items) | ≥ 90% | **${pct(r.detectionPower.rate)}** (${String(r.detectionPower.fires)}/${String(r.detectionPower.trials)}) |`,
    "",
    "Regenerate with `pnpm calibration` — deterministic, seeded, $0. Full detail in [evals/calibration/RESULTS.md](evals/calibration/RESULTS.md).",
  ];
  return lines.join("\n");
}

export function renderResultsMd(r) {
  const lines = [
    "# Calibration results",
    "",
    "Generated by `pnpm calibration` — never edited by hand. CI regenerates and",
    "fails on drift (SPEC §12/§14 M3). Both sims are pure and seeded",
    "(`core/calibration.ts`) — no `Math.random`, no ambient clock, no network,",
    "no key. Re-running produces byte-identical numbers.",
    "",
    `- generated: ${r.generatedAt}`,
    `- item pool: ${String(r.itemCount)} items, each drawn at a shared baseline pass rate; bootstrap \`B = ${fmt(r.bootstrapB)}\``,
    "",
    "## False-positive rate (SPEC §12: \"200 null pairs drawn from identical per-item rates\")",
    "",
    "Both readings, every trial, draw independently from the SAME per-item rate — the null hypothesis that nothing changed. A false positive is any verdict other than `moved-within-noise`.",
    "",
    `- trials: ${String(r.falsePositive.trials)}`,
    `- fires (false positives): **${String(r.falsePositive.fires)}**`,
    `- rate: **${pct(r.falsePositive.rate)}**`,
    "- gate: ≤ 5% nominal, CI enforces ≤ 8/200 (a tighter, hedged bar)",
    "",
    "## Detection power (SPEC §12: \"200 pairs with a planted 20% degradation on 40 items\")",
    "",
    `${String(r.degradedCount)} of ${String(r.itemCount)} items (20%) carry a clean, known planted regression in the second reading; the rest keep the same background noise as the false-positive sim. Detection is any \`regressed\` verdict on \`overall\`.`,
    "",
    `- trials: ${String(r.detectionPower.trials)}`,
    `- detected: **${String(r.detectionPower.fires)}**`,
    `- rate: **${pct(r.detectionPower.rate)}**`,
    "- gate: ≥ 90% (power floor)",
    "",
  ];
  return lines.join("\n");
}

export function injectReadme(readme, block) {
  const begin = readme.indexOf(BEGIN);
  const end = readme.indexOf(END);
  if (begin === -1 || end === -1 || end < begin) {
    throw new Error("README.md is missing the <!-- calibration:begin/end --> markers");
  }
  return `${readme.slice(0, begin + BEGIN.length)}\n${block}\n${readme.slice(end)}`;
}

async function generate() {
  // Requires `pnpm --filter tiltmeter build` first — imports the compiled
  // dist rather than re-implementing the sims in plain JS, so there is
  // exactly one source of truth for the calibration math (core/calibration.ts).
  const dist = await import("../packages/tiltmeter/dist/index.js");
  const falsePositive = dist.runNullPairCalibration();
  const detectionPower = dist.runPlantedDegradationCalibration();
  return {
    generatedAt: new Date().toISOString(),
    itemCount: dist.CALIBRATION_ITEM_COUNT,
    trials: dist.CALIBRATION_TRIALS,
    bootstrapB: dist.CALIBRATION_BOOTSTRAP_B,
    degradedCount: dist.CALIBRATION_DEGRADED_COUNT,
    falsePositive,
    detectionPower,
  };
}

async function main() {
  const check = process.argv.includes("--check");

  if (check) {
    const results = JSON.parse(readFileSync(LATEST, "utf8"));
    const block = renderReadmeBlock(results);
    const resultsMd = renderResultsMd(results);
    const readme = readFileSync(README, "utf8");
    const injected = injectReadme(readme, block);

    let failed = false;
    let committedResults = "";
    try {
      committedResults = readFileSync(RESULTS_MD, "utf8");
    } catch {
      // missing file = drift
    }
    if (committedResults !== resultsMd) {
      console.error("DRIFT: evals/calibration/RESULTS.md does not match evals/calibration/results/latest.json");
      failed = true;
    }
    if (readme !== injected) {
      console.error("DRIFT: the README calibration block does not match evals/calibration/results/latest.json");
      failed = true;
    }
    if (failed) {
      console.error("Run `pnpm calibration` and commit the regenerated artifacts.");
      process.exit(1);
    }
    console.log("calibration-report --check: README block and RESULTS.md match latest.json");
    return;
  }

  const results = await generate();
  mkdirSync(RESULTS_DIR, { recursive: true });
  writeFileSync(LATEST, `${JSON.stringify(results, null, 2)}\n`);
  writeFileSync(RESULTS_MD, renderResultsMd(results));
  const readme = readFileSync(README, "utf8");
  writeFileSync(README, injectReadme(readme, renderReadmeBlock(results)));
  console.log(
    "calibration-report: wrote evals/calibration/results/latest.json, evals/calibration/RESULTS.md, and injected the README block",
  );
}

await main();
